# Домашнее задание к занятию «Python для анализа данных: numpy и scipy»
### Преподаватель: Константин Башевой
**Домашнее задание**

**Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

**Задание 3**
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

**Задание 4**
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

**Задание 5**
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

# Решение.

**Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
N = 10
arr = np.arange(N-1, -1,-1)
arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
diag_ = np.eye(N,dtype=int) * arr
print(diag_,f'Сумма всех элементов матрицы = {diag_.sum()}', sep = '\n\n')

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]

Сумма всех элементов матрицы = 45


**Задание 3**
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [4]:
import pandas as pd

In [9]:
ratings = pd.read_csv('ml-latest/ratings.csv')
movies = pd.read_csv('ml-latest/movies.csv')
#print(ratings.head())
#print(movies.head())

In [37]:
joined = ratings.merge(movies, on ='movieId')
filtred = joined[joined['rating'] == 5]
ranked = filtred.groupby('title').count().sort_values('movieId', ascending = False)

In [38]:
ranked.head(1).index[0]

'Shawshank Redemption, The (1994)'

**Задание 4**
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [12]:
    power = pd.read_csv('power.csv')

In [101]:
power[(power['category'].isin([4,12,21])) &
      (power['country'].isin(['Latvia','Lithuania','Estonia'])) & 
      (power['quantity'] > 0) &
      (power['year'].between(2005,2010))
     ]


country  year  quantity  category
10617     Estonia  2008       1.0         4
10620     Estonia  2005       1.0         4
11156   Lithuania  2008       1.0         4
11158   Lithuania  2006       1.0         4
11159   Lithuania  2005       1.0         4
12755     Estonia  2008       1.0         4
12758     Estonia  2005       1.0         4
13294   Lithuania  2008       1.0         4
13296   Lithuania  2006       1.0         4
13297   Lithuania  2005       1.0         4
15525     Estonia  2008       1.0         4
15528     Estonia  2005       1.0         4
16068   Lithuania  2008       1.0         4
16070   Lithuania  2006       1.0         4
16071   Lithuania  2005       1.0         4
17675     Estonia  2008       1.0         4
17678     Estonia  2005       1.0         4
18218   Lithuania  2008       1.0         4
18220   Lithuania  2006       1.0         4
18221   Lithuania  2005       1.0         4
19854     Estonia  2008       1.0         4
19856     Estonia  2006       3.0         4
19857     Estonia  2005       6.0         4
20511   Lithuania  2008       1.0         4
20513   Lithuania  2006       1.0         4
20514   Lithuania  2005       1.0         4
21902     Estonia  2006       3.0         4
21903     Estonia  2005       5.0         4
25743     Estonia  2008       1.0         4
25746     Estonia  2005       1.0         4
...           ...   ...       ...       ...
248555     Latvia  2005    2166.0        21
248672  Lithuania  2010    3768.0        21
248673  Lithuania  2009    4909.0        21
248674  Lithuania  2008    4655.0        21
248675  Lithuania  2007    4613.0        21
248676  Lithuania  2006    4587.0        21
248677  Lithuania  2005    4556.0        21
251648  Lithuania  2009    1183.0        21
251649  Lithuania  2008    1183.0        21
251650  Lithuania  2007    1183.0        21
251651  Lithuania  2006    1183.0        21
251652  Lithuania  2005    1183.0        21
253561    Estonia  2010     108.0        21
253562    Estonia  2009     104.0        21
253563    Estonia  2008      77.0        21
253564    Estonia  2007      50.0        21
253565    Estonia  2006      31.0        21
253566    Estonia  2005      31.0        21
253962     Latvia  2010      32.0        21
253963     Latvia  2009      32.0        21
253964     Latvia  2008      28.0        21
253965     Latvia  2007      26.0        21
253966     Latvia  2006      27.0        21
253967     Latvia  2005      27.0        21
253981  Lithuania  2010     133.0        21
253982  Lithuania  2009      98.0        21
253983  Lithuania  2008      54.0        21
253984  Lithuania  2007      47.0        21
253985  Lithuania  2006      31.0        21
253986  Lithuania  2005       1.0        21

[347 rows x 4 columns]

Object `pd.between()` not found.


In [87]:
power[power['year'].between(2005,2007)]['year'].unique()

array([2007, 2006, 2005], dtype=int64)

In [50]:
power.sort_values('country')['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Anguilla', 'Antarctic Fisheries', 'Antigua and Barbuda',
       'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan',
       'Bolivia (Plur. State of)', 'Bonaire, St Eustatius, Saba',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Cayman Islands', 'Central African Rep.', 'Chad',
       'Chile', 'China', 'China, Hong Kong SAR', 'China, Macao SAR',
       'Colombia', 'Commonwealth of Independent States (CIS)', 'Comoros',
       'Congo', 'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba',
       'Curaçao', 'Cyprus', 'Czechia', 'Czechoslovakia (former)',
       "Côte d'Ivoire", 'Dem. Rep. of the Congo', 

**Задание 5**
Решите систему уравнений:

In [ ]:
import numpy as np

In [ ]:
from numpy import linalg

In [ ]:
a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3])

In [ ]:
solve = linalg.solve(a,b)

In [ ]:
print('x = {}\ny = {}\nz = {}'.format(*solve))

In [ ]:
np.allclose(np.dot(a,solve),b)