# Домашнее задание к занятию «Python для анализа данных: numpy и scipy»
### Преподаватель: Константин Башевой
**Домашнее задание**

**Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

**Задание 3**
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

**Задание 4**
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

**Задание 5**
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

# Решение.

**Задание 1**
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

In [2]:
N = 10
arr = np.arange(N-1, -1,-1)
arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
diag_ = np.eye(N,dtype=int) * arr
print(diag_,f'Сумма всех элементов матрицы = {diag_.sum()}', sep = '\n\n')

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]

Сумма всех элементов матрицы = 45


**Задание 3**
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [4]:
import pandas as pd

In [5]:
ratings = pd.read_csv('ml-latest/ratings.csv')
movies = pd.read_csv('ml-latest/movies.csv')
#print(ratings.head())
#print(movies.head())

In [6]:
joined = ratings.merge(movies, on ='movieId')
filtred = joined[joined['rating'] == 5]
ranked = filtred.groupby('title').count().sort_values('movieId', ascending = False)

In [7]:
ranked.head(1).index[0]

'Shawshank Redemption, The (1994)'

**Задание 4**
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [8]:
    power = pd.read_csv('power.csv')

In [9]:
power[(power['category'].isin([4,12,21])) &
      (power['country'].isin(['Latvia','Lithuania','Estonia'])) & 
      (power['quantity'] > 0) &
      (power['year'].between(2005,2010))
     ]['quantity'].sum()


240580.0

**Задание 5**
Решите систему уравнений:

In [10]:
import numpy as np

In [11]:
from numpy import linalg

In [12]:
a = np.array([[4,2,1],[1,3,0],[0,5,4]])
b = np.array([4,12,-3])

In [13]:
solve = linalg.solve(a,b)

In [14]:
print('x = {}\ny = {}\nz = {}'.format(*solve))

x = 0.4666666666666668
y = 3.844444444444444
z = -5.555555555555555


In [15]:
np.allclose(np.dot(a,solve),b)

True